### ISSUE TITLE
Удаления анимации после окончания.

### ISSUE THREAD

**Issue by ynhhoJ** [lJohhnyl/Corso-RolePlay#11]
Использую такую анимацию при написание чего-нибудь в чат-е:
`ApplyAnimation(playerid,"PED","IDLE_chat",4.1,0,1,1,1,1,1);`
Анимация проигрывается и потом персонаж замирает в определённом положение, поэтому я решил удалять анимацию таким способом:
`ApplyAnimation(playerid,"PED","IDLE_chat",4.1,0,1,1,1,1,1);`
`defer OnPlayerClearAnimation[6000](playerid);`
И сам таймер:
`timer OnPlayerClearAnimation[500](playerid)
{
	ApplyAnimation(playerid,"CARRY","crry_prtial",4.0,0,0,0,0,0,1);
}`
Но, проблема в том что когда сам таймер срабатывается с отчисткой анимацией, персонажа как-будто ударяют током на 10 миллисекунд и это сильно заметно...
Как можно исправить?

**Comment by eXeGOODER** [comment]
http://wiki.sa-mp.com/wiki/ClearAnimations

**Comment by ynhhoJ** [comment]
Решено.
